# Based on https://github.com/ist-dsi/docker-kerberos
version: "2"
services:
  kdc-standalone:
    container_name: 'kdc-standalone'
    hostname: 'kdc-standalone'
    build: .
    volumes:
      # This is needed otherwise there won't be enough entropy to generate a new kerberos realm
      - /dev/urandom:/dev/random
    ports:
#      - "749:749"
#      - "88:88/udp"
      - "2222:22"
